// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhROpc2xnRuSPi2FrArgQAh0NR_9UK3oU',
    appId: '1:146661084104:web:10eff9eb3d9e75b79b8efd',
    messagingSenderId: '146661084104',
    projectId: 'chatapp-150a5',
    authDomain: 'chatapp-150a5.firebaseapp.com',
    storageBucket: 'chatapp-150a5.appspot.com',
    measurementId: 'G-81GCBG6VR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw9Kdnuvj2rXLhWBHP4gY9vU6rH7qnZDg',
    appId: '1:146661084104:android:7a0d351d51d76ac39b8efd',
    messagingSenderId: '146661084104',
    projectId: 'chatapp-150a5',
    storageBucket: 'chatapp-150a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3kW8v6nTLotYqOB6tq3X5tr7UYrkU_Do',
    appId: '1:146661084104:ios:4c5c5f970d9c0f5c9b8efd',
    messagingSenderId: '146661084104',
    projectId: 'chatapp-150a5',
    storageBucket: 'chatapp-150a5.appspot.com',
    iosClientId: '146661084104-ojbktlfvdh968mb5vg0lup6kgs984i78.apps.googleusercontent.com',
    iosBundleId: 'chatApp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3kW8v6nTLotYqOB6tq3X5tr7UYrkU_Do',
    appId: '1:146661084104:ios:4c5c5f970d9c0f5c9b8efd',
    messagingSenderId: '146661084104',
    projectId: 'chatapp-150a5',
    storageBucket: 'chatapp-150a5.appspot.com',
    iosClientId: '146661084104-ojbktlfvdh968mb5vg0lup6kgs984i78.apps.googleusercontent.com',
    iosBundleId: 'chatApp.chatApp',
  );
}
